[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.4"
  NODE_VERSION = "18"

[context.production.environment]
  HUGO_ENV = "production"
  TINA_PUBLIC_IS_LOCAL = "false"